### ISSUE TITLE
merge compSPI/LatentSpaceVisualizer repo here

### ISSUE THREAD

**Issue by fredericpoitevin** [compSPI/ioSPI#1]
Move content from https://github.com/compSPI/LatentSpaceVisualizer

**Comment by ninamiolane** [comment]
Could be linked to dimension reduction too, and therefore could also maybe be within `reduceSPI`?

**Comment by fredericpoitevin** [comment]
That works too! 

Although I'm wondering what would be the best option: visualization tools specific to each repo or a centralized approach (that was my implicit assumption here, thinking `ioSPI` could be where we maintain visualization code)?

https://github.com/compSPI/LatentSpaceBuilder on the other hand should definitely be merged with `reduceSPI` eventually.

**Comment by fredericpoitevin** [comment]
@ninamiolane let's maybe close this and revisit later?

**Comment by ninamiolane** [comment]
Sounds good!
