### ISSUE TITLE
Implement link with OSF for storing data

### ISSUE THREAD

**Issue by geoffwoollard** [compSPI/ioSPI#20]
Look into how to store particle stack data sets on OSF
- how to push to OSF
- how to pull from OSF

How does the API work?

How can the user in ioSPI query for different datasets?

How long does it take to download data? What would be a reasonable size of "small" / "med" / "large" (e.g. 30s of download time vs 15 min).

https://osf.io/ 
https://www.cos.io/products/osf

**Comment by geoffwoollard** [comment]
@arjunsingh3600 perhaps you would be a good lead on this?

I'm going to make a small particle stack (with existing code, not the tem simulator wrapper) and then you can have that to use for this issue.

**Comment by geoffwoollard** [comment]
https://youtu.be/dLEIhJESIQA

**Comment by geoffwoollard** [comment]
Tasks
1. Make datasets OSF project page (maybe can be used for"datasets paper" later)
2. Put datasets (Geoff will provide for now) 
3. Figure out how to programatically use OSF's API to get publically accessible dataset from OSF to local, through ioSPI https://developer.osf.io/

**Comment by geoffwoollard** [comment]
See this file download.OSF.file.R for how to download files from OSF. It's in R, so port to Python
https://osf.io/hkpjb/

We see that we can access a json object and get a dictionary of dictionaries of dictionaries... see the line with `json_data$data$links$download` (i.e. ['json_data'['data']['links']['download'] in Python). This is just a URL we can use to download things from.

Consider the example from the youtube video walk through, fm4gc.
- page it lives in browser : https://osf.io/fm4gc/ 
- rendered in browser : https://mfr.osf.io/render?url=https://osf.io/fm4gc/?direct%26mode=render%26action=download%26mode=render
- downloadable url : https://osf.io/download/fm4gc/

So in general, it seems that to download file GUID, you just need to get it from https://osf.io/download/GUID/

**Comment by arjunsingh3600** [comment]
Hi Geoff,
I wanted to get some clarification regarding the organization of the OSF.io page.

The current plan for the page is as follows -

- The project data will be grouped by molecules into components.
- Each molecule component would further be divided into "particle stack" components. (For different parameters eg: noise, tem simulator, etc)
- Each "particle stack component" would contain a .star file (with metadata for each particle slice) and a particle stack file.
- Detailed simulation parameters for each particle stack will be stored in the wiki or read-me at a "particle stack" component level

I have organized the current project in the proposed setup [here ](https://osf.io/tj8ya/?view_only=dcc4581e44434f42a4e4a210fc81449e)

For the upcoming competition, our understanding is that the data will be uploaded by us and 
hence the priority is providing users of the page easy data retrieval and download access (as compared to also providing a data upload mechanism).
Could you please provide some feedback for the workflow above? In addition, some input on the following would be greatly appreciated-

- How large/diverse is the expected dataset for the upcoming hackathon (in terms of number of different molecules/particle stacks)? 
- What would be properties that the particle stacks should be categorized/labeled with? eg- noise, simulator type, one of the simulator configurations, etc. (These are the properties the user would search/navigate for)
- Is there a preference between having the user navigate the project page directly to retrieve data or using API Calls (or a module that is a part of IOSPI)?

**Comment by geoffwoollard** [comment]
> * How large/diverse is the expected dataset for the upcoming hackathon (in terms of number of different molecules/particle stacks)?

That depends on the typical download speed. Can you have some (download speed, etc) numbers based on the particle stack I gave you? This will help decide. But right off the bat, I'm thinking 100, 1k, 10k, 100k and maybe up to 1 M.

Khanh suggested several types of molecules. So let's do those first. 

I'll reply more later.

**Comment by arjunsingh3600** [comment]
I did some sample downloads to get a rough estimate of times. It seems like the API is fairly responsive and the majority of the time is taken by the download itself (which would depend on the user's connection/location).  
For the sample file (~879 Mb)-

Internet Download Speed | Download Time

200 Mbps |  <1 min
20- 40 Mbps  | 5 -3 mins
10 Mbps |  15 mins
4 Mbps | 20 - 40 mins

(Note: These could vary depending on the user's location/bandwidth.)

**Comment by arjunsingh3600** [comment]
@geoffwoollard @kdd-ubc As discussed in our previous meeting, I wanted to confirm the tags for datasets in storage. So far I have,

-  Noise : [yes,no]
- Pixel Size

**Comment by geoffwoollard** [comment]
pixel size: this will be a float around the values 0.5 - 2.0 Angstroms. I would think values like 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0 would be a good to simulate the upload to the cloud. You can use `pixel_size_ang` for now.

noise: there is the type of noise (e.g. gaussian white noise, poisson shot noise) and the amount of noise (for gaussian white noise it's just one number, e.g. signal to noise ratio 0.1, 0.03, 0.01, 0.003; for poisson shot noise it's different and I'd have to take a closer look - hopefully it's just one number for the "dose"). You can use `noise_type`, `noise_level` for now.

ctf: there will be different distributions of ctf (uniform, gaussian, mixture of gaussians), and also the complexity of the ctf (rotationally symetric 1D ctf, 2 fold astigmatism, higher order abberations). For now use `ctf_type` (taking options rotationally_symmetric, two_fold_astigmatism), and `ctf_distribution` (which will have some details about the distribution used to simulate the ctf, for instance "uniform defocus_ang" or "gaussian astigmatism_angle"). The ctf has several parameters, and each of these parameters can be a random variable with its own distribution, so I think all the details needed will only fit in a config/yaml file in the OSF entry, not in the OSF string fields, which will be some sort of semi-informative short hand.

rotations: `rotation_distribution`: just include "uniform_on_sphere" for now. Down the line we will extend this to preferred rotations.

I think this is good for now.

**Comment by fredericpoitevin** [comment]
Hi @arjunsingh3600 sorry for taking so long.

I think the structure you propose on OSF works great. 
What would be useful is to have a "real life" example that I and others could play with; it would help identify problems if there are any.

I see "Internal" and "Data" on OSF: the one relevant for us is the latter right? I guess the former is for your own development?

Under "Data", I see the "EMD_3683" entry: is that what we would call a "Molecule" (in the language you used above)?
Then I gather that "EMD_3683_sample_1" would be one "Component".

And then you will have several datasets under each "Component". 
The actual names of the datasets could be randomly generated as long as there is a parameter file under the dataset directory that uniquely defines the dataset (e.g. using the tags @geoffwoollard has listed above). 
\The dataset tags could reflect the content of the parameter file.

**Comment by arjunsingh3600** [comment]
Thank you for the comments!

I will be working on building some "real-life" datasets before our next call using the tags @geoffwoollard proposed, so we can discuss them and address any issues that may arise.

@fredericpoitevin That is right. The "Internal" component is only used as a target for calls for unit tests and the actual datasets will be housed in "Data". 

To summarise, The current planned structure is planned like so - 
- "Data" would contain several "Molecule" components. for eg : "EMD_3683"
- Each molecule would contain various dataset components. for eg: "EMD_3683_sample_1", "EMD_3683_(some random key)"
- Each dataset component will contain the actual particle files, metadata, and parameter files corresponding to a single dataset. These components will also be the ones that are tagged.

Note in the TEMUpload (PR #25) the project page and components are referred to as "Nodes" (for cohesion with the language used in the OSF.io API documentation).

**Comment by fredericpoitevin** [comment]
Sounds great, @arjunsingh3600 !

**Comment by fredericpoitevin** [comment]
Will be documented in #30  where notebooks will detail the process and illustrate on real examples. Closing this.
