### ISSUE TITLE
Auto-assignment of maintainers for PR reviews

### ISSUE THREAD

**Issue by fredericpoitevin** [compSPI/ioSPI#28]
Should we enforce it and use this tool? https://github.com/apps/auto-assign

**Comment by ninamiolane** [comment]
As you wish! 

The downside that I could see is that sometimes people open pull requests just to see how the pull request behaves, but the code is not ready for review --- in this case we would get a notification to review something, for nothing.

But we could try and see1

**Comment by fredericpoitevin** [comment]
Yes I agree - but since many recent PR have not been reviewed by us, it seems to be necessary. 
I'll assign one reviewer, the repo maintainer, who can assign other reviewers if necessary.

And we should make clear that a review will automatically request changes without going through the code when tests are not passing.

**Comment by geoffwoollard** [comment]
> The downside that I could see is that sometimes people open pull requests just to see how the pull request behaves, but the code is not ready for review --- in this case we would get a notification to review something, for nothing.

this can be done on someone's fork
