### ISSUE TITLE
Write tutorial notebook for ioSPI (includes uses of OSF)

### ISSUE THREAD

**Issue by geoffwoollard** [compSPI/ioSPI#30]
They will first need to be generated in simSPI. See https://github.com/compSPI/simSPI/issues/49

Then they will need to be obtained through ioSPI.

**Comment by geoffwoollard** [comment]
Suggested deadline: Jan 28

**Comment by ninamiolane** [comment]
@geoffwoollard @arjunsingh3600 what is the update on this? 

Since we merged the PR related to OSF, the infrastructure to do this should be in place.

I suggest that this task becomes: 

"Implement a notebook tutorial for ioSPI and, as part of it, show how to download the datasets from OSF."

**Comment by fredericpoitevin** [comment]
Milestone with deadline on March 10th: https://github.com/compSPI/simSPI/milestone/1

**Comment by fredericpoitevin** [comment]
#64 will close this once merged.
