### ISSUE TITLE
Existing tests failing due to dependancy issues

### ISSUE THREAD

**Issue by arjunsingh3600** [compSPI/ioSPI#34]
While running tests in #25, I noticed none of the tests in the repo were passing due to failures when importing modules from simSPI and ioSPI. 

for simSPI imports, I suspect the failures are caused by simSPI not being a part of the environment.yml file.

**Comment by geoffwoollard** [comment]
https://github.com/compSPI/ioSPI/pull/38#issuecomment-1023736662

**Comment by geoffwoollard** [comment]
Closed because no longer an issue.
