### ISSUE TITLE
Remove FFT code.

### ISSUE THREAD

**Issue by fredericpoitevin** [compSPI/ioSPI#45]
Once/if merge, https://github.com/compSPI/compSPI/pull/28 will provide the relevant functions for performing FFT.

**Comment by geoffwoollard** [comment]
Code dependencies in 

https://github.com/compSPI/ioSPI/blob/master/tests/test_fourier.py
https://github.com/compSPI/simSPI/blob/master/simSPI/multislice.py
https://github.com/compSPI/simSPI/blob/master/tests/test_multislice.py

I wrote all of this and I'm fine removing it. I can also refactor it with the FFT in compSPI. I'd like to do something with multislice eventually, but I can remove it for now and come back to it later (in pytorch).

**Comment by fredericpoitevin** [comment]
If possible, a refactor with FFT from compSPI would be great.

**Comment by geoffwoollard** [comment]
ok sure, I can do that.

**Comment by geoffwoollard** [comment]
Once these are merged this issue can be closed.

https://github.com/compSPI/ioSPI/pull/49
https://github.com/compSPI/simSPI/pull/66
