### ISSUE TITLE
Error in write_crd_file

### ISSUE THREAD

**Issue by ninamiolane** [compSPI/ioSPI#47]
From a discussion with @luis-sribeiro:

"A test that failed is related to the write_crd_file function. I believe this function has a little problem (that I corrected in my PR). If you look at the for loops in this function, we have n_particles^2 iterations in total instead of n_particles iterations. So, the coordinate file will have additional lines that will be ignored. And because of the inner for loop, the particles are created in the same positions, but with different rotations, which basically generates a micrograph with a single particle image (they are all overlapped on top of each other).

What the function is generating: https://pastebin.com/wa8GfNRd
What it should generate: https://pastebin.com/bge6aKhH "

**Comment by jedyeo** [comment]
Was this was addressed in https://github.com/compSPI/simSPI/pull/57? If so thank you!

**Comment by fredericpoitevin** [comment]
@jedyeo is this issue resolved? Can we close?

**Comment by calhep** [comment]
@fredericpoitevin this issue has since been resolved!
