### ISSUE TITLE
consistent use of uppercase and lowercase for ioSPI and other repos

### ISSUE THREAD

**Issue by fredericpoitevin** [compSPI/ioSPI#5]
According to PEP8 naming conventions, modules need to be all-lowercases (https://www.python.org/dev/peps/pep-0008/#package-and-module-names). 

I think it is a good idea but that means we will need to rename all the repos like that: ioSPI ==> iospi, reduceSPI ==> reducespi, etc.

Should we do that?

**Comment by ninamiolane** [comment]
Yes, iospi, compspi, reducespi etc are less readable without the uppercase letters :/ should we make an exception (everywhere, also in all the filenames), and keep SPI in uppercase? E.g. ioSPI.yml, reduceSPI.yml etc?

**Comment by fredericpoitevin** [comment]
Ah yes I'd be happy with this exception! As long as "SPI" is always at the end of the name, never at the beginning and never followed by something else (to avoid what would look like a camelcase) this could work :D 

Let's do that?
