### ISSUE TITLE
pytest not generating report

### ISSUE THREAD

**Issue by fredericpoitevin** [compSPI/ioSPI#6]
At the moment, pytest fails to generate reports (which cascades to codecov errors too):

> Coverage.py warning: No data was collected. (no-data-collected)
> tests/test_iotools/test_atomic_models.py ..                              [100%]WARNING: Failed to generate report: No data to report.
> /usr/share/miniconda/lib/python3.8/site-packages/pytest_cov/plugin.py:271: PytestWarning: Failed to generate report: No data to report.

**Comment by ninamiolane** [comment]
I think this is because no test have been run yet. If you create a placeholder test, maybe it could be fixed?

**Comment by ninamiolane** [comment]
^In this logic, maybe try to remove the inheritance `(unittest.TestCase)`? we shouldn't need it with pytest.

**Comment by fredericpoitevin** [comment]
> I think this is because no test have been run yet. If you create a placeholder test, maybe it could be fixed?

Thanks! It turned out it was the arguments I was giving to `pytest` that were causing the issue. Removing those fixed it: https://github.com/compSPI/ioSPI/commit/59aeb5dfbe6203e7a8ae3e30b72a48d437cd1cac

I still need to figure out how to get the code coverage reports though

**Comment by geoffwoollard** [comment]
I think the code coverage reports are being generated, so closing.
