### ISSUE TITLE
During pre-commit, black fails

### ISSUE THREAD

**Issue by bongjinkoo** [compSPI/ioSPI#87]
During pre-commit, black fails with `ImportError: cannot import name '_unicodefun' from 'click'`.
This is a known error and can be fixed by installing the latest version of black (https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click).
In `.pre-commit-config.yaml`, black is set to `21.8b0`. Does this happen to others? @ninamiolane. Is it possible not to set the version here, so that the latest version gets installed?

**Comment by ninamiolane** [comment]
Good catch! Could you try 22.3.0 @bongjinkoo 

This is the version[ used here](https://github.com/geomstats/geomstats/blob/master/.pre-commit-config.yaml) and it seems to work.

**Comment by bongjinkoo** [comment]
Yes, I did and it works. Do I set this version in the config file then?

**Comment by bongjinkoo** [comment]
Done.

**Comment by ninamiolane** [comment]
Fantastic, thank you!
